version: '3'

services:
  molli-frontend:
    image: moleculemaker/molli-frontend:staging
    container_name: molli-frontend
    build:
      context: .
    env_file: .env
    ports:
      - 8989:80
    restart: unless-stopped

    volumes:
     - ./assets/config/:/usr/share/nginx/html/assets/config:ro
     #- ./dist/molli:/usr/share/nginx/html:ro
